concurrency:
  cancel-in-progress: false
  group: "pages"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5
      - name: Filter artifact
        run: |
          mkdir _site
          find \( -name "*.css" \
            -o -name "*.html" \
            -o -name "*.js" \
            \) -not -path "./_site/*" \
            -exec cp --parents {} _site/ \;
        shell: sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
name: Deploy configuration app to GitHub Pages
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  id-token: write
  pages: write
